version: "3"
services:
  spring-boot:
    build:
      context: ./flaschenbook-spring-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  react:
    build:
      context: ./flaschenbook-react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"

  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd/etc:/fluentd/etc

  # 추가적인 서비스 및 네트워크 설정이 필요할 수 있습니다.
