global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "spring-actuator-prometheus"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 2s
    static_configs:
      # - targets: ["host.docker.internal:80"]
      - targets:
          ["ecs-flb-backend-alb-1415357375.ap-northeast-2.elb.amazonaws.com"]
